name: ci_entry
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  socket_io_client: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#f7fcfc"
  image: ./assets/splash.jpg

  android_12:
    image: assets/splash.jpg
    icon_background_color: "#f7fcfc"
    image_dark: assets/splash.jpg
    icon_background_color_dark: "#121212"
